name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.13, 1.14, 1.15]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Install Linters
        run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.34.1"
      - name: Lint
        env:
          GO111MODULE: "on"
        run: golangci-lint run --disable-all --deadline=10m --enable=gofmt --enable=gosimple --enable=unconvert --enable=ineffassign --enable=govet ./...
      - name: Test
        env:
          GORACE: "halt_on_error=1"
          GO111MODULE: "on"
        run: |
          go test -v -race -tags safe ./spew
          go test -v -race -tags testcgo ./spew -covermode=atomic -coverprofile=profile.cov
      - name: Goveralls
        env:
          GO111MODULE: "on"
        run: |
          go get -v github.com/mattn/goveralls
          goveralls -coverprofile=profile.cov -service=travis-ci
